#define PIN_LED_VERDE 25
#define PIN_LED_ROJO 26
#define PIN_LED_AZUL 27

#define CONFIG_LED_VERDE pinMode(PIN_LED_VERDE, OUTPUT)
#define SET_LED_VERDE digitalWrite(PIN_LED_VERDE, HIGH)
#define CLR_LED_VERDE digitalWrite(PIN_LED_VERDE, LOW)

#define CONFIG_LED_ROJO pinMode(PIN_LED_ROJO, OUTPUT)
#define SET_LED_ROJO digitalWrite(PIN_LED_ROJO, HIGH)
#define CLR_LED_ROJO digitalWrite(PIN_LED_ROJO, LOW)

#define CONFIG_LED_AZUL pinMode(PIN_LED_AZUL, OUTPUT)
#define SET_LED_AZUL digitalWrite(PIN_LED_AZUL, HIGH)
#define CLR_LED_AZUL digitalWrite(PIN_LED_AZUL, LOW)

#define PRENDER_LED_VERDE CLR_LED_VERDE
#define PRENDER_LED_ROJO CLR_LED_ROJO
#define PRENDER_LED_AZUL CLR_LED_AZUL

#define APAGAR_LED_VERDE SET_LED_VERDE
#define APAGAR_LED_AZUL SET_LED_AZUL
#define APAGAR_LED_ROJO SET_LED_ROJO

#define TOGLE_LED_AZUL digitalWrite(PIN_LED_AZUL, !digitalRead(PIN_LED_AZUL));
